name: marmiteur
description: Receive recipe details given a URL.
version: 2.0.0
repository: https://github.com/dougy147/marmiteur

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  beautiful_soup_dart: ^0.3.0
  collection: ^1.18.0
  http: ^1.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
